-- liquibase formatted sql

-- changeset admin:1
CREATE TABLE IF NOT EXISTS devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    power_consumption FLOAT,
    room VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status IN ('ON', 'OFF')),
    target_value INTEGER,
    type VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sensor_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    humidity FLOAT NOT NULL,
    temperature FLOAT NOT NULL,
    timestamp TIMESTAMP(6)
);

-- changeset admin:2
INSERT INTO devices (name, type, status, target_value, room, power_consumption) VALUES
('Основне світло', 'LIGHT', 'OFF', 100, 'Вітальня', 30.0),
('Торшер біля дивана', 'LIGHT', 'OFF', 80, 'Вітальня', 15.0),
('Стельове світло', 'LIGHT', 'OFF', 100, 'Спальня', 20.0),
('Світло', 'LIGHT', 'OFF', 100, 'Кухня', 20.0),
('Кавоварка', 'COFFEE_MAKER', 'OFF', null, 'Кухня', 1200.0),
('Чайник', 'KETTLE', 'OFF', null, 'Кухня', 2000.0),
('Посудомийна машина', 'DISHWASHER', 'OFF', null, 'Кухня', 1800.0),
('Телевізор', 'TV', 'OFF', 50, 'Вітальня', 150.0),
('Стереосистема', 'STEREO', 'OFF', 30, 'Вітальня', 100.0),
('Датчик розбиття скла', 'SECURITY_SENSOR', 'ON', null, 'Вітальня', 2.0),
('Кондиціонер', 'AC', 'OFF', 22, 'Спальня', 900.0),
('Праска', 'APPLIANCE', 'OFF', null, 'Спальня', 2200.0),
('Робот-пилосос', 'VACUUM', 'OFF', null, 'Коридор', 40.0),
('Тепла підлога', 'HEATED_FLOOR', 'OFF', 25, 'Ванна', 500.0),
('Датчик руху', 'MOTION_SENSOR', 'OFF', null, 'Коридор', 5.0),
('Датчик відкриття дверей', 'DOOR_SENSOR', 'OFF', null, 'Коридор', 5.0)
ON CONFLICT (name) DO NOTHING;