spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.sql

server:
  port: 8080

weather:
  url: "https://api.open-meteo.com/v1/forecast?latitude=${WEATHER_LAT}&longitude=${WEATHER_LON}&current_weather=true"

ai:
  groq:
    api-key: ${GROQ_API_KEY}
    url: "https://api.groq.com/openai/v1/chat/completions"
  tavily:
    api-key: ${TAVILY_API_KEY}